name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  pull_request:
    branches: [ main ]
    types: [closed]
jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/dhananjay25/AKS-CICD
            azure-pipeline-name: 'dhananjaykurekar25.AKS-CICD-With-UnitTest'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
